-- Functions, triggers, event triggers and comments.
--
-- GENERATED by scripts/db-gen-custom-migration.mjs from a database with all
-- 42 supabase/migrations applied. Drizzle Kit cannot express any of these, so
-- they are owned here as hand-maintained SQL and must be edited by adding a
-- NEW migration, never by changing this file (Drizzle does not verify
-- migration hashes, so an edit to an applied file is silently ignored).
--
-- is_admin() is intentionally absent: 0000 defines it, because the RLS
-- policies in 0001 reference it at CREATE POLICY time.
--
-- Excluded on purpose (see docs/db-flip/unversioned-prod-objects.md):
--   functions: update_inventory_on_order
--   triggers:  on_order_confirmed, meta-conversions-purchase
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.add_product(p_name text, p_slug text, p_base_price numeric, p_description text DEFAULT NULL::text, p_short_description text DEFAULT NULL::text, p_sku text DEFAULT NULL::text, p_category_id uuid DEFAULT NULL::uuid, p_brand_id uuid DEFAULT NULL::uuid, p_gender product_gender DEFAULT 'unisex'::product_gender, p_material text DEFAULT NULL::text, p_care_instructions text DEFAULT NULL::text, p_weight numeric DEFAULT NULL::numeric, p_dimensions jsonb DEFAULT NULL::jsonb, p_compare_at_price numeric DEFAULT NULL::numeric, p_is_featured boolean DEFAULT false, p_requires_shipping boolean DEFAULT true, p_track_inventory boolean DEFAULT true, p_allow_backorder boolean DEFAULT false, p_min_order_quantity integer DEFAULT 1, p_max_order_quantity integer DEFAULT NULL::integer, p_meta_title text DEFAULT NULL::text, p_meta_description text DEFAULT NULL::text, p_tags text[] DEFAULT NULL::text[], p_low_stock_threshold integer DEFAULT 10, p_variants jsonb DEFAULT '[]'::jsonb, p_initial_stock integer DEFAULT 0, p_user_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_product_id UUID;
  v_variant_id UUID;
  v_variant JSONB;
  v_result JSONB;
  v_variants_result JSONB[] := '{}';
BEGIN
  -- Insert product
  INSERT INTO products (
    name, slug, base_price, description, short_description, sku, category_id, brand_id,
    gender, material, care_instructions, weight, dimensions,
    compare_at_price, is_featured, requires_shipping,
    track_inventory, allow_backorder, min_order_quantity, max_order_quantity,
    meta_title, meta_description, tags, low_stock_threshold
  ) VALUES (
    p_name, p_slug, p_base_price, p_description, p_short_description, p_sku, p_category_id, p_brand_id,
    p_gender, p_material, p_care_instructions, p_weight, p_dimensions,
    p_compare_at_price, p_is_featured, p_requires_shipping,
    p_track_inventory, p_allow_backorder, p_min_order_quantity, p_max_order_quantity,
    p_meta_title, p_meta_description, p_tags, p_low_stock_threshold
  ) RETURNING id INTO v_product_id;

  -- Insert variants
  FOR v_variant IN SELECT * FROM jsonb_array_elements(p_variants)
  LOOP
    INSERT INTO product_variants (
      product_id, sku, name, size, color, color_code, material, weight,
      price, compare_at_price, barcode, sort_order
    ) VALUES (
      v_product_id,
      COALESCE((v_variant->>'sku'), p_sku || '-' || (v_variant->>'size') || '-' || (v_variant->>'color')),
      COALESCE((v_variant->>'name'), p_name || ' - ' || (v_variant->>'size') || ' ' || (v_variant->>'color')),
      v_variant->>'size',
      v_variant->>'color',
      v_variant->>'color_code',
      v_variant->>'material',
      (v_variant->>'weight')::DECIMAL,
      COALESCE((v_variant->>'price')::DECIMAL, p_base_price),
      (v_variant->>'compare_at_price')::DECIMAL,
      v_variant->>'barcode',
      COALESCE((v_variant->>'sort_order')::INTEGER, 0)
    ) RETURNING id INTO v_variant_id;

    -- Create initial inventory record
    INSERT INTO inventory (variant_id, quantity, reorder_point, reorder_quantity)
    VALUES (v_variant_id, p_initial_stock, p_low_stock_threshold, p_low_stock_threshold * 2);

    -- Log initial stock movement if stock > 0
    IF p_initial_stock > 0 THEN
      PERFORM log_inventory_movement(
        v_variant_id,
        'restock',
        'purchase_order',
        p_initial_stock,
        NULL, -- order_id
        NULL, -- order_item_id
        p_user_id,
        'INITIAL_STOCK',
        'Initial stock for new product',
        NULL, -- cost_per_unit (removed cost_price reference)
        'main'
      );
    END IF;

    -- Add variant to result
    v_variants_result := array_append(v_variants_result, jsonb_build_object(
      'id', v_variant_id,
      'sku', COALESCE((v_variant->>'sku'), p_sku || '-' || (v_variant->>'size') || '-' || (v_variant->>'color')),
      'name', COALESCE((v_variant->>'name'), p_name || ' - ' || (v_variant->>'size') || ' ' || (v_variant->>'color')),
      'size', v_variant->>'size',
      'color', v_variant->>'color',
      'initial_stock', p_initial_stock
    ));
  END LOOP;

  -- Build result
  v_result := jsonb_build_object(
    'success', true,
    'product_id', v_product_id,
    'product_name', p_name,
    'variants', to_jsonb(v_variants_result),
    'message', 'Product added successfully'
  );

  RETURN v_result;
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', SQLERRM,
      'message', 'Failed to add product'
    );
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION add_product(p_name text, p_slug text, p_base_price numeric, p_description text, p_short_description text, p_sku text, p_category_id uuid, p_brand_id uuid, p_gender product_gender, p_material text, p_care_instructions text, p_weight numeric, p_dimensions jsonb, p_compare_at_price numeric, p_is_featured boolean, p_requires_shipping boolean, p_track_inventory boolean, p_allow_backorder boolean, p_min_order_quantity integer, p_max_order_quantity integer, p_meta_title text, p_meta_description text, p_tags text[], p_low_stock_threshold integer, p_variants jsonb, p_initial_stock integer, p_user_id uuid) IS 'Adds a new product with variants and initial inventory (cost_price removed)';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.apply_inventory_on_order_fulfilled()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  r RECORD;
BEGIN
  IF NEW.fulfillment_status = 'fulfilled'::fulfillment_status
     AND OLD.fulfillment_status IS DISTINCT FROM 'fulfilled'::fulfillment_status THEN
    FOR r IN
      SELECT variant_id, quantity
      FROM public.order_items
      WHERE order_id = NEW.id
    LOOP
      UPDATE public.inventory
      SET
        reserved_quantity = GREATEST(0, reserved_quantity - r.quantity),
        updated_at = now()
      WHERE variant_id = r.variant_id;
    END LOOP;
  END IF;

  RETURN NEW;
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION apply_inventory_on_order_fulfilled() IS 'On fulfillment, releases the reservation only. inventory.quantity was already
   decremented by the application at order-creation time.';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.cancel_order(p_order_id uuid, p_reason text DEFAULT NULL::text, p_user_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_result JSONB;
  v_order_status order_status;
  v_order_item RECORD;
  v_movement_id UUID;
  v_restored_items JSONB[] := '{}';
  v_total_restored INTEGER := 0;
BEGIN
  -- Get current order status
  SELECT status INTO v_order_status
  FROM orders
  WHERE id = p_order_id;

  -- Check if order can be cancelled
  IF v_order_status IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Order not found'
    );
  END IF;

  IF v_order_status IN ('cancelled', 'delivered', 'refunded') THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Order cannot be cancelled in current status: ' || v_order_status
    );
  END IF;

  -- Update order status
  UPDATE orders
  SET
    status = 'cancelled',
    internal_notes = COALESCE(internal_notes, '') ||
      CASE WHEN internal_notes IS NOT NULL THEN '; ' ELSE '' END ||
      'Cancelled on ' || NOW()::TEXT ||
      CASE WHEN p_reason IS NOT NULL THEN ': ' || p_reason ELSE '' END,
    updated_at = NOW()
  WHERE id = p_order_id;

  -- Restore stock for each order item
  FOR v_order_item IN
    SELECT oi.id, oi.variant_id, oi.quantity, oi.product_name, oi.variant_name
    FROM order_items oi
    WHERE oi.order_id = p_order_id
  LOOP
    -- Restore stock
    UPDATE inventory
    SET quantity = quantity + v_order_item.quantity
    WHERE variant_id = v_order_item.variant_id;

    -- Log movement
    v_movement_id := log_inventory_movement(
      v_order_item.variant_id,
      'cancel',
      'order_cancelled',
      v_order_item.quantity,
      p_order_id,
      v_order_item.id,
      p_user_id,
      NULL, -- reference_number
      'Stock restored due to order cancellation',
      NULL, -- cost_per_unit
      'main'
    );

    -- Add to restored items
    v_restored_items := array_append(v_restored_items, jsonb_build_object(
      'order_item_id', v_order_item.id,
      'variant_id', v_order_item.variant_id,
      'product_name', v_order_item.product_name,
      'variant_name', v_order_item.variant_name,
      'quantity_restored', v_order_item.quantity,
      'movement_id', v_movement_id
    ));

    v_total_restored := v_total_restored + v_order_item.quantity;
  END LOOP;

  v_result := jsonb_build_object(
    'success', true,
    'order_id', p_order_id,
    'total_items_restored', array_length(v_restored_items, 1),
    'total_quantity_restored', v_total_restored,
    'restored_items', to_jsonb(v_restored_items),
    'message', 'Order cancelled and stock restored successfully'
  );

  RETURN v_result;
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', SQLERRM,
      'message', 'Failed to cancel order'
    );
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION cancel_order(p_order_id uuid, p_reason text, p_user_id uuid) IS 'Cancels an order and restores stock to inventory';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.check_low_stock()
 RETURNS TABLE(product_id uuid, product_name text, variant_id uuid, variant_name text, current_stock integer, low_stock_threshold integer, reorder_point integer, reorder_quantity integer)
 LANGUAGE plpgsql
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    p.id as product_id,
    p.name as product_name,
    pv.id as variant_id,
    pv.name as variant_name,
    i.quantity as current_stock,
    p.low_stock_threshold,
    i.reorder_point,
    i.reorder_quantity
  FROM products p
  JOIN product_variants pv ON p.id = pv.product_id
  JOIN inventory i ON pv.id = i.variant_id
  WHERE p.is_active = true
    AND pv.is_active = true
    AND i.quantity <= COALESCE(p.low_stock_threshold, 10)
  ORDER BY i.quantity ASC;
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION check_low_stock() IS 'Tested and working - returns products below low stock threshold';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.create_order(user_id uuid, email text, phone text, items jsonb, billing_address jsonb, shipping_address jsonb, notes text, session_id text, payment_method text DEFAULT 'cash'::text, guest_token text DEFAULT NULL::text, p_tax_amount numeric DEFAULT 0, p_shipping_amount numeric DEFAULT 0, p_discount_amount numeric DEFAULT 0)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  new_order_id uuid;
  order_number text := concat('ORD-', to_char(NOW(), 'YYYYMMDDHH24MISS'));
  item record;
  created_order jsonb;
  guest_token_expires timestamptz;
  product_data record;
  variant_data record;
  v_subtotal numeric;
BEGIN
  IF user_id IS NULL AND guest_token IS NOT NULL THEN
    guest_token_expires := NOW() + INTERVAL '1 month';
  ELSE
    guest_token_expires := NULL;
  END IF;

  INSERT INTO public.orders(
    id, order_number, user_id, email, phone,
    subtotal, tax_amount, shipping_amount, discount_amount, total_amount,
    status, payment_status, fulfillment_status,
    billing_address, shipping_address, notes,
    session_id, guest_token, guest_token_expires,
    created_at, updated_at
  )
  VALUES (
    gen_random_uuid(), order_number, user_id, email, phone,
    0, 0, 0, 0, 0,
    'pending'::order_status, 'pending'::payment_status, 'unfulfilled'::fulfillment_status,
    billing_address, shipping_address, notes,
    session_id, guest_token, guest_token_expires,
    now(), now()
  )
  RETURNING id INTO new_order_id;

  FOR item IN SELECT * FROM jsonb_to_recordset(items) AS (
    product_id uuid,
    variant_id uuid,
    quantity int,
    unit_price numeric
  )
  LOOP
    PERFORM 1 FROM public.inventory
    WHERE variant_id = item.variant_id
      AND (quantity - reserved_quantity) >= item.quantity
    LIMIT 1;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Insufficient inventory for variant %', item.variant_id;
    END IF;

    SELECT p.name AS product_name, p.sku AS product_sku
    INTO product_data
    FROM public.products p
    WHERE p.id = item.product_id;

    SELECT pv.name AS variant_name, pv.sku AS variant_sku
    INTO variant_data
    FROM public.product_variants pv
    WHERE pv.id = item.variant_id;

    INSERT INTO public.order_items(
      id, order_id, product_id, variant_id,
      product_name, variant_name, sku,
      quantity, unit_price, total_price,
      created_at
    )
    VALUES (
      gen_random_uuid(), new_order_id, item.product_id, item.variant_id,
      COALESCE(product_data.product_name, ''),
      COALESCE(variant_data.variant_name, ''),
      COALESCE(variant_data.variant_sku, product_data.product_sku, ''),
      item.quantity, item.unit_price, (item.quantity * item.unit_price),
      now()
    );

    UPDATE public.inventory
    SET reserved_quantity = reserved_quantity + item.quantity,
        updated_at = now()
    WHERE variant_id = item.variant_id;
  END LOOP;

  SELECT COALESCE(SUM(total_price), 0)
  INTO v_subtotal
  FROM public.order_items
  WHERE order_id = new_order_id;

  UPDATE public.orders
  SET
    subtotal = v_subtotal,
    tax_amount = COALESCE(p_tax_amount, 0),
    shipping_amount = COALESCE(p_shipping_amount, 0),
    discount_amount = COALESCE(p_discount_amount, 0),
    total_amount = v_subtotal
      + COALESCE(p_tax_amount, 0)
      + COALESCE(p_shipping_amount, 0)
      - COALESCE(p_discount_amount, 0),
    updated_at = now()
  WHERE id = new_order_id;

  INSERT INTO public.payments(
    id, order_id, payment_method, amount, currency, status, created_at
  )
  VALUES (
    gen_random_uuid(),
    new_order_id,
    payment_method::payment_method,
    (SELECT total_amount FROM public.orders WHERE id = new_order_id),
    'BDT',
    'pending',
    now()
  );

  IF user_id IS NOT NULL THEN
    DELETE FROM public.cart_items ci
    WHERE ci.user_id = create_order.user_id
      AND ci.variant_id IN (
        SELECT oi.variant_id
        FROM public.order_items oi
        WHERE oi.order_id = new_order_id
      );
  ELSE
    IF session_id IS NOT NULL THEN
      DELETE FROM public.cart_items ci
      WHERE ci.session_id = create_order.session_id
        AND ci.variant_id IN (
          SELECT oi.variant_id
          FROM public.order_items oi
          WHERE oi.order_id = new_order_id
        );
    END IF;
  END IF;

  SELECT row_to_json(o.*) INTO created_order
  FROM (
    SELECT *
    FROM public.orders
    WHERE id = new_order_id
  ) o;

  RETURN created_order;
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION create_order(user_id uuid, email text, phone text, items jsonb, billing_address jsonb, shipping_address jsonb, notes text, session_id text, payment_method text, guest_token text, p_tax_amount numeric, p_shipping_amount numeric, p_discount_amount numeric) IS 'Creates order with line items; applies tax/shipping/discount to total and payment amount.';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.decrease_stock(p_variant_id uuid, p_quantity integer, p_order_id uuid DEFAULT NULL::uuid, p_order_item_id uuid DEFAULT NULL::uuid, p_user_id uuid DEFAULT NULL::uuid, p_reference_number text DEFAULT NULL::text, p_notes text DEFAULT NULL::text, p_location text DEFAULT 'main'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_movement_id UUID;
  v_current_quantity INTEGER;
  v_new_quantity INTEGER;
BEGIN
  IF p_quantity <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Quantity must be greater than 0'
    );
  END IF;

  SELECT COALESCE(quantity, 0) INTO v_current_quantity
  FROM inventory
  WHERE variant_id = p_variant_id AND location = p_location;

  IF v_current_quantity < p_quantity THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Insufficient stock. Available: ' || v_current_quantity || ', Required: ' || p_quantity
    );
  END IF;

  v_new_quantity := v_current_quantity - p_quantity;

  UPDATE inventory
  SET
    quantity = quantity - p_quantity,
    updated_at = NOW()
  WHERE variant_id = p_variant_id AND location = p_location;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Inventory record not found for variant: ' || p_variant_id
    );
  END IF;

  v_movement_id := log_inventory_movement(
    p_variant_id,
    'sale',
    'customer_order',
    -p_quantity,
    p_order_id,
    p_order_item_id,
    p_user_id,
    p_reference_number,
    p_notes,
    NULL,
    p_location
  );

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Stock decreased successfully',
    'data', jsonb_build_object(
      'variant_id', p_variant_id,
      'location', p_location,
      'quantity_decreased', p_quantity,
      'previous_quantity', v_current_quantity,
      'new_quantity', v_new_quantity,
      'movement_id', v_movement_id
    )
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Failed to decrease stock: ' || SQLERRM
    );
END;
$function$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.get_guest_order(p_order_id uuid, p_guest_token text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  result jsonb;
BEGIN
  IF p_order_id IS NULL OR p_guest_token IS NULL OR length(trim(p_guest_token)) = 0 THEN
    RETURN NULL;
  END IF;

  SELECT
    jsonb_build_object(
      'id', o.id,
      'order_number', o.order_number,
      'status', o.status,
      'payment_status', o.payment_status,
      'fulfillment_status', o.fulfillment_status,
      'subtotal', o.subtotal,
      'tax_amount', o.tax_amount,
      'shipping_amount', o.shipping_amount,
      'discount_amount', o.discount_amount,
      'total_amount', o.total_amount,
      'created_at', o.created_at,
      'order_items',
      COALESCE(
        (
          SELECT jsonb_agg(
            jsonb_build_object(
              'id', oi.id,
              'product_id', oi.product_id,
              'variant_id', oi.variant_id,
              'product_name', oi.product_name,
              'variant_name', oi.variant_name,
              'sku', oi.sku,
              'quantity', oi.quantity,
              'unit_price', oi.unit_price,
              'total_price', oi.total_price,
              'product',
              (
                SELECT jsonb_build_object(
                  'id', p.id,
                  'name', p.name,
                  'slug', p.slug,
                  'images',
                  COALESCE(
                    (
                      SELECT jsonb_agg(
                        jsonb_build_object(
                          'id', pi.id,
                          'url', pi.url,
                          'alt_text', pi.alt_text,
                          'is_primary', pi.is_primary,
                          'sort_order', pi.sort_order
                        )
                        ORDER BY pi.is_primary DESC NULLS LAST, pi.sort_order NULLS LAST
                      )
                      FROM public.product_images pi
                      WHERE pi.product_id = p.id
                    ),
                    '[]'::jsonb
                  )
                )
                FROM public.products p
                WHERE p.id = oi.product_id
              ),
              'variant',
              (
                SELECT jsonb_build_object(
                  'id', pv.id,
                  'name', pv.name,
                  'size', pv.size,
                  'color', pv.color
                )
                FROM public.product_variants pv
                WHERE pv.id = oi.variant_id
              )
            )
            ORDER BY oi.created_at
          )
          FROM public.order_items oi
          WHERE oi.order_id = o.id
        ),
        '[]'::jsonb
      )
    )
  INTO result
  FROM public.orders o
  WHERE o.id = p_order_id
    AND o.guest_token = p_guest_token
    AND (o.guest_token_expires IS NULL OR o.guest_token_expires > now());

  RETURN result;
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION get_guest_order(p_order_id uuid, p_guest_token text) IS 'Returns order confirmation fields + line items with product images when guest_token matches.';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.get_inventory_summary(p_product_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_result JSONB;
  v_variant_summary JSONB[] := '{}';
  v_variant RECORD;
  v_total_stock INTEGER := 0;
  v_total_reserved INTEGER := 0;
  v_total_available INTEGER := 0;
  v_low_stock_variants INTEGER := 0;
BEGIN
  -- Get variant summaries
  FOR v_variant IN
    SELECT
      pv.id as variant_id,
      pv.name as variant_name,
      pv.sku,
      pv.size,
      pv.color,
      COALESCE(i.quantity, 0) as stock_quantity,
      COALESCE(i.reserved_quantity, 0) as reserved_quantity,
      COALESCE(i.available_quantity, 0) as available_quantity,
      COALESCE(i.reorder_point, 0) as reorder_point,
      COALESCE(i.reorder_quantity, 0) as reorder_quantity,
      p.low_stock_threshold,
      CASE WHEN COALESCE(i.quantity, 0) <= COALESCE(p.low_stock_threshold, 10) THEN true ELSE false END as is_low_stock
    FROM product_variants pv
    LEFT JOIN inventory i ON pv.id = i.variant_id
    JOIN products p ON pv.product_id = p.id
    WHERE pv.product_id = p_product_id
    ORDER BY pv.sort_order, pv.name
  LOOP
    v_variant_summary := array_append(v_variant_summary, to_jsonb(v_variant));

    v_total_stock := v_total_stock + v_variant.stock_quantity;
    v_total_reserved := v_total_reserved + v_variant.reserved_quantity;
    v_total_available := v_total_available + v_variant.available_quantity;

    IF v_variant.is_low_stock THEN
      v_low_stock_variants := v_low_stock_variants + 1;
    END IF;
  END LOOP;

  v_result := jsonb_build_object(
    'product_id', p_product_id,
    'total_stock', v_total_stock,
    'total_reserved', v_total_reserved,
    'total_available', v_total_available,
    'low_stock_variants', v_low_stock_variants,
    'total_variants', array_length(v_variant_summary, 1),
    'variants', to_jsonb(v_variant_summary)
  );

  RETURN v_result;
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION get_inventory_summary(p_product_id uuid) IS 'Returns comprehensive inventory summary for a product';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.log_inventory_movement(p_variant_id uuid, p_movement_type movement_type, p_reason movement_reason, p_quantity integer, p_order_id uuid DEFAULT NULL::uuid, p_order_item_id uuid DEFAULT NULL::uuid, p_user_id uuid DEFAULT NULL::uuid, p_reference_number text DEFAULT NULL::text, p_notes text DEFAULT NULL::text, p_cost_per_unit numeric DEFAULT NULL::numeric, p_location text DEFAULT 'main'::text)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_movement_id UUID;
  v_previous_quantity INTEGER;
  v_new_quantity INTEGER;
  v_on_hand INTEGER;
  v_total_cost DECIMAL(10,2);
BEGIN
  v_on_hand := COALESCE(
    (
      SELECT quantity
      FROM inventory
      WHERE variant_id = p_variant_id AND location = p_location
      LIMIT 1
    ),
    0
  );

  IF p_movement_type IN ('reserve', 'unreserve')
     OR (p_movement_type = 'sale' AND p_reason = 'customer_order') THEN
    v_previous_quantity := v_on_hand;
    v_new_quantity := v_on_hand;
  ELSE
    v_new_quantity := v_on_hand;
    v_previous_quantity := v_on_hand - p_quantity;
  END IF;

  v_total_cost := p_quantity * COALESCE(p_cost_per_unit, 0);

  INSERT INTO inventory_movements (
    variant_id,
    movement_type,
    reason,
    quantity,
    previous_quantity,
    new_quantity,
    order_id,
    order_item_id,
    user_id,
    reference_number,
    notes,
    cost_per_unit,
    total_cost,
    location
  ) VALUES (
    p_variant_id,
    p_movement_type,
    p_reason,
    p_quantity,
    v_previous_quantity,
    v_new_quantity,
    p_order_id,
    p_order_item_id,
    p_user_id,
    p_reference_number,
    p_notes,
    p_cost_per_unit,
    v_total_cost,
    p_location
  ) RETURNING id INTO v_movement_id;

  RETURN v_movement_id;
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION log_inventory_movement(p_variant_id uuid, p_movement_type movement_type, p_reason movement_reason, p_quantity integer, p_order_id uuid, p_order_item_id uuid, p_user_id uuid, p_reference_number text, p_notes text, p_cost_per_unit numeric, p_location text) IS 'Logs inventory movements. previous_quantity/new_quantity reflect on-hand quantity; for reserve/unreserve and sale+customer_order (reserved-only change), both match current on-hand.';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.process_order_completion(p_order_id uuid, p_user_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_result JSONB;
  v_order_item RECORD;
  v_movement_id UUID;
  v_processed_items JSONB[] := '{}';
  v_total_processed INTEGER := 0;
BEGIN
  -- Get order status
  IF NOT EXISTS (SELECT 1 FROM orders WHERE id = p_order_id) THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Order not found'
    );
  END IF;

  -- Process each order item
  FOR v_order_item IN
    SELECT oi.id, oi.variant_id, oi.quantity, oi.product_name, oi.variant_name
    FROM order_items oi
    WHERE oi.order_id = p_order_id
  LOOP
    -- Convert reserved stock to sold (decrease reserved quantity)
    UPDATE inventory
    SET reserved_quantity = reserved_quantity - v_order_item.quantity
    WHERE variant_id = v_order_item.variant_id;

    -- Log movement
    v_movement_id := log_inventory_movement(
      v_order_item.variant_id,
      'sale',
      'customer_order',
      -v_order_item.quantity, -- Negative for decrease
      p_order_id,
      v_order_item.id,
      p_user_id,
      NULL, -- reference_number
      'Stock sold - order completed',
      NULL, -- cost_per_unit
      'main'
    );

    -- Add to processed items
    v_processed_items := array_append(v_processed_items, jsonb_build_object(
      'order_item_id', v_order_item.id,
      'variant_id', v_order_item.variant_id,
      'product_name', v_order_item.product_name,
      'variant_name', v_order_item.variant_name,
      'quantity_sold', v_order_item.quantity,
      'movement_id', v_movement_id
    ));

    v_total_processed := v_total_processed + v_order_item.quantity;
  END LOOP;

  v_result := jsonb_build_object(
    'success', true,
    'order_id', p_order_id,
    'total_items_processed', array_length(v_processed_items, 1),
    'total_quantity_sold', v_total_processed,
    'processed_items', to_jsonb(v_processed_items),
    'message', 'Order completion processed successfully'
  );

  RETURN v_result;
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', SQLERRM,
      'message', 'Failed to process order completion'
    );
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION process_order_completion(p_order_id uuid, p_user_id uuid) IS 'Converts reserved stock to sold stock';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.product_images_enforce_single_primary()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.is_primary IS TRUE THEN
    UPDATE public.product_images
    SET is_primary = FALSE
    WHERE product_id = NEW.product_id
      AND is_primary = TRUE
      AND id <> COALESCE(NEW.id, '00000000-0000-0000-0000-000000000000'::uuid);
  END IF;
  RETURN NEW;
END;
$function$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.release_inventory_for_deleted_order()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT variant_id, quantity
    FROM public.order_items
    WHERE order_id = OLD.id
  LOOP
    UPDATE public.inventory
    SET
      quantity          = quantity + r.quantity,
      reserved_quantity = GREATEST(0, reserved_quantity - r.quantity),
      updated_at        = now()
    WHERE variant_id = r.variant_id;
  END LOOP;
  RETURN OLD;
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION release_inventory_for_deleted_order() IS 'Before an order row is deleted, restores inventory.quantity and releases
   reserved_quantity for every line item, mirroring what the cancel API does.';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.reserve_stock(p_variant_id uuid, p_quantity integer, p_order_id uuid DEFAULT NULL::uuid, p_order_item_id uuid DEFAULT NULL::uuid, p_user_id uuid DEFAULT NULL::uuid, p_reference_number text DEFAULT NULL::text, p_notes text DEFAULT NULL::text, p_location text DEFAULT 'main'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_movement_id UUID;
  v_current_quantity INTEGER;
  v_current_reserved INTEGER;
  v_new_reserved INTEGER;
BEGIN
  IF p_quantity <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Quantity must be greater than 0'
    );
  END IF;

  SELECT
    COALESCE(quantity, 0),
    COALESCE(reserved_quantity, 0)
  INTO v_current_quantity, v_current_reserved
  FROM inventory
  WHERE variant_id = p_variant_id AND location = p_location;

  IF (v_current_quantity - v_current_reserved) < p_quantity THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Insufficient available stock. Available: ' || (v_current_quantity - v_current_reserved) || ', Required: ' || p_quantity
    );
  END IF;

  v_new_reserved := v_current_reserved + p_quantity;

  UPDATE inventory
  SET
    reserved_quantity = reserved_quantity + p_quantity,
    updated_at = NOW()
  WHERE variant_id = p_variant_id AND location = p_location;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Inventory record not found for variant: ' || p_variant_id
    );
  END IF;

  v_movement_id := log_inventory_movement(
    p_variant_id,
    'reserve',
    'checkout_reserve',
    p_quantity,
    p_order_id,
    p_order_item_id,
    p_user_id,
    p_reference_number,
    p_notes,
    NULL,
    p_location
  );

  RETURN jsonb_build_object(
    'success', true,
    'message', 'Stock reserved successfully',
    'data', jsonb_build_object(
      'variant_id', p_variant_id,
      'location', p_location,
      'quantity_reserved', p_quantity,
      'previous_reserved', v_current_reserved,
      'new_reserved', v_new_reserved,
      'available_quantity', v_current_quantity - v_new_reserved,
      'movement_id', v_movement_id
    )
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Failed to reserve stock: ' || SQLERRM
    );
END;
$function$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.restock_inventory(p_variant_id uuid, p_quantity integer, p_cost_per_unit numeric DEFAULT NULL::numeric, p_reference_number text DEFAULT NULL::text, p_notes text DEFAULT NULL::text, p_user_id uuid DEFAULT NULL::uuid, p_location text DEFAULT 'main'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_result JSONB;
  v_movement_id UUID;
  v_current_quantity INTEGER;
  v_new_quantity INTEGER;
BEGIN
  -- Validate quantity
  IF p_quantity <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Quantity must be greater than 0'
    );
  END IF;

  -- Get current quantity
  SELECT COALESCE(quantity, 0) INTO v_current_quantity
  FROM inventory
  WHERE variant_id = p_variant_id AND location = p_location;

  -- Calculate new quantity
  v_new_quantity := v_current_quantity + p_quantity;

  -- Update inventory using UPSERT
  INSERT INTO inventory (variant_id, quantity, location)
  VALUES (p_variant_id, p_quantity, p_location)
  ON CONFLICT (variant_id, location)
  DO UPDATE SET
    quantity = inventory.quantity + p_quantity,
    updated_at = NOW();

  -- Log movement
  v_movement_id := log_inventory_movement(
    p_variant_id,
    'restock',
    'purchase_order',
    p_quantity,
    NULL, -- order_id
    NULL, -- order_item_id
    p_user_id,
    p_reference_number,
    p_notes,
    p_cost_per_unit,
    p_location
  );

  -- Get updated quantity
  SELECT quantity INTO v_new_quantity
  FROM inventory
  WHERE variant_id = p_variant_id AND location = p_location;

  -- Return success result
  RETURN jsonb_build_object(
    'success', true,
    'message', 'Inventory restocked successfully',
    'data', jsonb_build_object(
      'variant_id', p_variant_id,
      'location', p_location,
      'quantity_added', p_quantity,
      'previous_quantity', v_current_quantity,
      'new_quantity', v_new_quantity,
      'movement_id', v_movement_id
    )
  );

EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Failed to restock inventory: ' || SQLERRM
    );
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION restock_inventory(p_variant_id uuid, p_quantity integer, p_cost_per_unit numeric, p_reference_number text, p_notes text, p_user_id uuid, p_location text) IS 'Tested and working - increases stock quantity and logs movement';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.return_item(p_order_id uuid, p_order_item_id uuid, p_quantity integer, p_reason text DEFAULT NULL::text, p_is_resellable boolean DEFAULT true, p_user_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_result JSONB;
  v_order_item RECORD;
  v_movement_id UUID;
  v_current_quantity INTEGER;
  v_new_status order_status;
BEGIN
  IF p_quantity <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Quantity must be greater than 0'
    );
  END IF;

  SELECT oi.*, o.status AS order_status
  INTO v_order_item
  FROM order_items oi
  JOIN orders o ON oi.order_id = o.id
  WHERE oi.id = p_order_item_id AND oi.order_id = p_order_id;

  IF v_order_item.id IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Order item not found'
    );
  END IF;

  IF p_quantity > v_order_item.quantity THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Return quantity cannot exceed ordered quantity',
      'ordered_quantity', v_order_item.quantity,
      'return_quantity', p_quantity
    );
  END IF;

  IF v_order_item.order_status NOT IN ('delivered', 'shipped') THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Order must be delivered or shipped to process return'
    );
  END IF;

  IF p_is_resellable THEN
    SELECT COALESCE(quantity, 0) INTO v_current_quantity
    FROM inventory
    WHERE variant_id = v_order_item.variant_id;

    UPDATE inventory
    SET quantity = quantity + p_quantity
    WHERE variant_id = v_order_item.variant_id;

    v_movement_id := log_inventory_movement(
      v_order_item.variant_id,
      'return',
      'customer_return',
      p_quantity,
      p_order_id,
      p_order_item_id,
      p_user_id,
      NULL,
      'Stock restored from customer return' ||
      CASE WHEN p_reason IS NOT NULL THEN ': ' || p_reason ELSE '' END,
      NULL,
      'main'
    );
  END IF;

  v_new_status := CASE
    WHEN (SELECT SUM(oi.quantity) FROM order_items oi WHERE oi.order_id = p_order_id) =
         (SELECT COALESCE(SUM(oi.quantity), 0) FROM order_items oi
          WHERE oi.order_id = p_order_id AND oi.id = p_order_item_id)
    THEN 'refunded'::order_status
    ELSE 'processing'::order_status
  END;

  UPDATE orders
  SET
    status = v_new_status,
    internal_notes = COALESCE(internal_notes, '') ||
      CASE WHEN internal_notes IS NOT NULL THEN '; ' ELSE '' END ||
      'Item returned on ' || NOW()::TEXT ||
      CASE WHEN p_reason IS NOT NULL THEN ': ' || p_reason ELSE '' END,
    updated_at = NOW()
  WHERE id = p_order_id;

  v_result := jsonb_build_object(
    'success', true,
    'order_id', p_order_id,
    'order_item_id', p_order_item_id,
    'quantity_returned', p_quantity,
    'is_resellable', p_is_resellable,
    'stock_restored', p_is_resellable,
    'movement_id', CASE WHEN p_is_resellable THEN v_movement_id ELSE NULL END,
    'new_order_status', v_new_status::text,
    'message', 'Item return processed successfully'
  );

  RETURN v_result;
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', SQLERRM,
      'message', 'Failed to process item return'
    );
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION return_item(p_order_id uuid, p_order_item_id uuid, p_quantity integer, p_reason text, p_is_resellable boolean, p_user_id uuid) IS 'Processes item returns and optionally restores stock';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.unreserve_stock(p_variant_id uuid, p_quantity integer, p_order_id uuid DEFAULT NULL::uuid, p_order_item_id uuid DEFAULT NULL::uuid, p_user_id uuid DEFAULT NULL::uuid, p_reference_number text DEFAULT NULL::text, p_notes text DEFAULT NULL::text, p_location text DEFAULT 'main'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_result JSONB;
  v_movement_id UUID;
  v_current_quantity INTEGER;
  v_current_reserved INTEGER;
  v_new_reserved INTEGER;
BEGIN
  -- Validate quantity
  IF p_quantity <= 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Quantity must be greater than 0'
    );
  END IF;

  -- Get current quantities
  SELECT
    COALESCE(quantity, 0),
    COALESCE(reserved_quantity, 0)
  INTO v_current_quantity, v_current_reserved
  FROM inventory
  WHERE variant_id = p_variant_id AND location = p_location;

  -- Check if we have enough reserved stock
  IF v_current_reserved < p_quantity THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Insufficient reserved stock. Reserved: ' || v_current_reserved || ', Required: ' || p_quantity
    );
  END IF;

  -- Calculate new reserved quantity
  v_new_reserved := v_current_reserved - p_quantity;

  -- Update inventory
  UPDATE inventory
  SET
    reserved_quantity = reserved_quantity - p_quantity,
    updated_at = NOW()
  WHERE variant_id = p_variant_id AND location = p_location;

  -- Check if update was successful
  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Inventory record not found for variant: ' || p_variant_id
    );
  END IF;

  -- Log movement
  v_movement_id := log_inventory_movement(
    p_variant_id,
    'unreserve',
    'payment_failed',
    -p_quantity, -- Negative quantity for unreserve
    p_order_id,
    p_order_item_id,
    p_user_id,
    p_reference_number,
    p_notes,
    NULL, -- cost_per_unit
    p_location
  );

  -- Return success result
  RETURN jsonb_build_object(
    'success', true,
    'message', 'Stock unreserved successfully',
    'data', jsonb_build_object(
      'variant_id', p_variant_id,
      'location', p_location,
      'quantity_unreserved', p_quantity,
      'previous_reserved', v_current_reserved,
      'new_reserved', v_new_reserved,
      'available_quantity', v_current_quantity - v_new_reserved,
      'movement_id', v_movement_id
    )
  );

EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'Failed to unreserve stock: ' || SQLERRM
    );
END;
$function$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.update_product(p_product_id uuid, p_name text DEFAULT NULL::text, p_slug text DEFAULT NULL::text, p_description text DEFAULT NULL::text, p_short_description text DEFAULT NULL::text, p_sku text DEFAULT NULL::text, p_category_id uuid DEFAULT NULL::uuid, p_brand_id uuid DEFAULT NULL::uuid, p_gender product_gender DEFAULT NULL::product_gender, p_material text DEFAULT NULL::text, p_care_instructions text DEFAULT NULL::text, p_weight numeric DEFAULT NULL::numeric, p_dimensions jsonb DEFAULT NULL::jsonb, p_base_price numeric DEFAULT NULL::numeric, p_compare_at_price numeric DEFAULT NULL::numeric, p_is_featured boolean DEFAULT NULL::boolean, p_requires_shipping boolean DEFAULT NULL::boolean, p_track_inventory boolean DEFAULT NULL::boolean, p_allow_backorder boolean DEFAULT NULL::boolean, p_min_order_quantity integer DEFAULT NULL::integer, p_max_order_quantity integer DEFAULT NULL::integer, p_meta_title text DEFAULT NULL::text, p_meta_description text DEFAULT NULL::text, p_tags text[] DEFAULT NULL::text[], p_low_stock_threshold integer DEFAULT NULL::integer, p_user_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_result JSONB;
  v_update_fields TEXT := '';
  v_field_value TEXT;
BEGIN
  -- Build dynamic update query
  IF p_name IS NOT NULL THEN
    v_update_fields := v_update_fields || 'name = $2, ';
  END IF;
  IF p_slug IS NOT NULL THEN
    v_update_fields := v_update_fields || 'slug = $3, ';
  END IF;
  IF p_description IS NOT NULL THEN
    v_update_fields := v_update_fields || 'description = $4, ';
  END IF;
  IF p_short_description IS NOT NULL THEN
    v_update_fields := v_update_fields || 'short_description = $5, ';
  END IF;
  IF p_sku IS NOT NULL THEN
    v_update_fields := v_update_fields || 'sku = $6, ';
  END IF;
  IF p_category_id IS NOT NULL THEN
    v_update_fields := v_update_fields || 'category_id = $7, ';
  END IF;
  IF p_brand_id IS NOT NULL THEN
    v_update_fields := v_update_fields || 'brand_id = $8, ';
  END IF;
  IF p_gender IS NOT NULL THEN
    v_update_fields := v_update_fields || 'gender = $9, ';
  END IF;
  IF p_material IS NOT NULL THEN
    v_update_fields := v_update_fields || 'material = $10, ';
  END IF;
  IF p_care_instructions IS NOT NULL THEN
    v_update_fields := v_update_fields || 'care_instructions = $11, ';
  END IF;
  IF p_weight IS NOT NULL THEN
    v_update_fields := v_update_fields || 'weight = $12, ';
  END IF;
  IF p_dimensions IS NOT NULL THEN
    v_update_fields := v_update_fields || 'dimensions = $13, ';
  END IF;
  IF p_base_price IS NOT NULL THEN
    v_update_fields := v_update_fields || 'base_price = $14, ';
  END IF;
  IF p_compare_at_price IS NOT NULL THEN
    v_update_fields := v_update_fields || 'compare_at_price = $15, ';
  END IF;
  IF p_is_featured IS NOT NULL THEN
    v_update_fields := v_update_fields || 'is_featured = $16, ';
  END IF;
  IF p_requires_shipping IS NOT NULL THEN
    v_update_fields := v_update_fields || 'requires_shipping = $17, ';
  END IF;
  IF p_track_inventory IS NOT NULL THEN
    v_update_fields := v_update_fields || 'track_inventory = $18, ';
  END IF;
  IF p_allow_backorder IS NOT NULL THEN
    v_update_fields := v_update_fields || 'allow_backorder = $19, ';
  END IF;
  IF p_min_order_quantity IS NOT NULL THEN
    v_update_fields := v_update_fields || 'min_order_quantity = $20, ';
  END IF;
  IF p_max_order_quantity IS NOT NULL THEN
    v_update_fields := v_update_fields || 'max_order_quantity = $21, ';
  END IF;
  IF p_meta_title IS NOT NULL THEN
    v_update_fields := v_update_fields || 'meta_title = $22, ';
  END IF;
  IF p_meta_description IS NOT NULL THEN
    v_update_fields := v_update_fields || 'meta_description = $23, ';
  END IF;
  IF p_tags IS NOT NULL THEN
    v_update_fields := v_update_fields || 'tags = $24, ';
  END IF;
  IF p_low_stock_threshold IS NOT NULL THEN
    v_update_fields := v_update_fields || 'low_stock_threshold = $25, ';
  END IF;

  -- Remove trailing comma and space
  v_update_fields := rtrim(v_update_fields, ', ');

  IF v_update_fields = '' THEN
    RETURN jsonb_build_object(
      'success', false,
      'message', 'No fields to update'
    );
  END IF;

  -- Execute update
  EXECUTE format('UPDATE products SET %s, updated_at = NOW() WHERE id = $1', v_update_fields)
  USING p_product_id, p_name, p_slug, p_description, p_short_description, p_sku,
        p_category_id, p_brand_id, p_gender, p_material, p_care_instructions,
        p_weight, p_dimensions, p_base_price, p_compare_at_price,
        p_is_featured, p_requires_shipping, p_track_inventory, p_allow_backorder,
        p_min_order_quantity, p_max_order_quantity, p_meta_title, p_meta_description,
        p_tags, p_low_stock_threshold;

  -- Check if any rows were updated
  IF FOUND THEN
    v_result := jsonb_build_object(
      'success', true,
      'product_id', p_product_id,
      'message', 'Product updated successfully'
    );
  ELSE
    v_result := jsonb_build_object(
      'success', false,
      'message', 'Product not found'
    );
  END IF;

  RETURN v_result;
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', SQLERRM,
      'message', 'Failed to update product'
    );
END;
$function$;
--> statement-breakpoint
COMMENT ON FUNCTION update_product(p_product_id uuid, p_name text, p_slug text, p_description text, p_short_description text, p_sku text, p_category_id uuid, p_brand_id uuid, p_gender product_gender, p_material text, p_care_instructions text, p_weight numeric, p_dimensions jsonb, p_base_price numeric, p_compare_at_price numeric, p_is_featured boolean, p_requires_shipping boolean, p_track_inventory boolean, p_allow_backorder boolean, p_min_order_quantity integer, p_max_order_quantity integer, p_meta_title text, p_meta_description text, p_tags text[], p_low_stock_threshold integer, p_user_id uuid) IS 'Updates product details with dynamic field updates (cost_price removed)';
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.update_product_stock_quantity()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Update the product's total stock quantity
  UPDATE products
  SET stock_quantity = (
    SELECT COALESCE(SUM(i.quantity), 0)
    FROM inventory i
    JOIN product_variants pv ON i.variant_id = pv.id
    WHERE pv.product_id = (
      SELECT pv2.product_id
      FROM product_variants pv2
      WHERE pv2.id = NEW.variant_id
    )
  )
  WHERE id = (
    SELECT pv.product_id
    FROM product_variants pv
    WHERE pv.id = NEW.variant_id
  );

  RETURN NEW;
END;
$function$;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_brands_updated_at ON public.brands;
--> statement-breakpoint
CREATE TRIGGER update_brands_updated_at BEFORE UPDATE ON public.brands FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_cart_items_updated_at ON public.cart_items;
--> statement-breakpoint
CREATE TRIGGER update_cart_items_updated_at BEFORE UPDATE ON public.cart_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_categories_updated_at ON public.categories;
--> statement-breakpoint
CREATE TRIGGER update_categories_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_inventory_updated_at ON public.inventory;
--> statement-breakpoint
CREATE TRIGGER update_inventory_updated_at BEFORE UPDATE ON public.inventory FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_product_stock_trigger ON public.inventory;
--> statement-breakpoint
CREATE TRIGGER update_product_stock_trigger AFTER INSERT OR DELETE OR UPDATE ON public.inventory FOR EACH ROW EXECUTE FUNCTION update_product_stock_quantity();
--> statement-breakpoint
DROP TRIGGER IF EXISTS trg_orders_apply_inventory_on_fulfilled ON public.orders;
--> statement-breakpoint
CREATE TRIGGER trg_orders_apply_inventory_on_fulfilled AFTER UPDATE OF fulfillment_status ON public.orders FOR EACH ROW EXECUTE FUNCTION apply_inventory_on_order_fulfilled();
--> statement-breakpoint
DROP TRIGGER IF EXISTS trg_orders_release_inventory_before_delete ON public.orders;
--> statement-breakpoint
CREATE TRIGGER trg_orders_release_inventory_before_delete BEFORE DELETE ON public.orders FOR EACH ROW EXECUTE FUNCTION release_inventory_for_deleted_order();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_orders_updated_at ON public.orders;
--> statement-breakpoint
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS enforce_single_primary ON public.product_images;
--> statement-breakpoint
CREATE TRIGGER enforce_single_primary BEFORE INSERT OR UPDATE OF is_primary, product_id ON public.product_images FOR EACH ROW EXECUTE FUNCTION product_images_enforce_single_primary();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_product_reviews_updated_at ON public.product_reviews;
--> statement-breakpoint
CREATE TRIGGER update_product_reviews_updated_at BEFORE UPDATE ON public.product_reviews FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_product_variants_updated_at ON public.product_variants;
--> statement-breakpoint
CREATE TRIGGER update_product_variants_updated_at BEFORE UPDATE ON public.product_variants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_products_updated_at ON public.products;
--> statement-breakpoint
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
--> statement-breakpoint
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
DROP TRIGGER IF EXISTS update_user_addresses_updated_at ON public.user_addresses;
--> statement-breakpoint
CREATE TRIGGER update_user_addresses_updated_at BEFORE UPDATE ON public.user_addresses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
--> statement-breakpoint
COMMENT ON TYPE public.payment_method IS 'Payment methods: cash (cash on delivery), online (stripe, paypal, etc.)';
--> statement-breakpoint
COMMENT ON CONSTRAINT inventory_variant_location_unique ON public.inventory IS 'Ensures one inventory record per variant per location';
--> statement-breakpoint
COMMENT ON TABLE public.brands IS 'RLS enabled - public access to active brands, admin access to all';
--> statement-breakpoint
COMMENT ON TABLE public.cart_items IS 'RLS enabled - users manage own cart, guests use session_id';
--> statement-breakpoint
COMMENT ON TABLE public.categories IS 'RLS enabled - public access to active categories, admin access to all';
--> statement-breakpoint
COMMENT ON TABLE public.conversations IS 'Chat conversations. user_id is null for guests. last_activity_at drives retention: guests are cleaned up after 48h, users after 90d (see /internal/chat/cleanup).';
--> statement-breakpoint
COMMENT ON TABLE public.courier_tracking_events IS 'Courier parcel tracking timeline — one row per status/tracking update (webhook or reconciliation poll). Backend-only (RLS enabled, no policies).';
--> statement-breakpoint
COMMENT ON TABLE public.inventory IS 'RLS enabled - public access to inventory data, admin access to all';
--> statement-breakpoint
COMMENT ON TABLE public.inventory_movements IS 'RLS enabled — only admins may SELECT/INSERT/UPDATE/DELETE directly; service/definer paths unaffected.';
--> statement-breakpoint
COMMENT ON TABLE public.kb_chunks IS 'RAG knowledge base for the customer chatbot — one row per embedded chunk (product, policy, or FAQ). embedding is voyage-3 (1024-dim).';
--> statement-breakpoint
COMMENT ON TABLE public.messages IS 'Individual chat turns. Cascade-deletes with its conversation — no separate cleanup needed.';
--> statement-breakpoint
COMMENT ON TABLE public.meta_capi_sent IS 'Tracks orders for which a Meta CAPI Purchase event was sent (dedupe webhook retries).';
--> statement-breakpoint
COMMENT ON TABLE public.orders IS 'RLS: users see own rows; admins full access; guests use order confirmation token flow.';
--> statement-breakpoint
COMMENT ON TABLE public.product_images IS 'RLS enabled - public access to all images, admin access to all';
--> statement-breakpoint
COMMENT ON TABLE public.product_reviews IS 'RLS enabled - public sees approved reviews, users manage own reviews';
--> statement-breakpoint
COMMENT ON TABLE public.product_variants IS 'RLS enabled - public access to active variants, admin access to all';
--> statement-breakpoint
COMMENT ON TABLE public.products IS 'RLS enabled - public access to active products, admin access to all';
--> statement-breakpoint
COMMENT ON TABLE public.profiles IS 'RLS enabled - users can manage own profile, admins can manage all';
--> statement-breakpoint
COMMENT ON COLUMN public.orders.email IS 'Customer email; NULL when not provided (e.g. guest checkout without email).';
