-- Sample Products Data for Footwear E-commerce
-- Migration: 003_sample_products.sql
--
-- No-op as of this edit: this used to insert generic placeholder catalog data
-- (Puma, Converse, Vans, etc.) that showed up on every fresh `supabase db reset`,
-- polluting local dev alongside the real catalog. Already applied on production
-- (tracked by version, not content), so this edit only affects fresh installs —
-- the real catalog now comes from supabase/seed.sql (a production data snapshot),
-- which runs after all migrations on `supabase db reset`.
